export const galleryItems = [
    {
      id: 1,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774238242/congdong_online-video-cutter.com_aaugtn.mp4",
      alt: "CONGCU.AI - Không Gian Vô Tận",
      text: "CONGCU.AI | Trí Tuệ AI - Không Gian Vô Tận",
      likes: 999,
      colSpan: "md:col-span-2 lg:col-span-2",
      rowSpan: "row-span-2",
      featured: true,
    },
    {
      id: 2,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774239005/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_1_lrluq0.mp4",
      alt: "CONGCU.AI - Vẻ Đẹp Ảo Ảnh",
      text: "CONGCU.AI | Trí Tuệ AI - Vẻ Đẹp Ảo Ảnh",
      likes: 888,
      colSpan: "",
      rowSpan: "row-span-4",
    },
    {
      id: 3,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774240461/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_3_ueldon.mp4",
      alt: "CONGCU.AI - Chuyển Động Tương Lai",
      text: "CONGCU.AI | Trí Tuệ AI - Chuyển Động Tương Lai",
      likes: 777,
      colSpan: "",
      rowSpan: "row-span-3",
    },
    {
      id: 4,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774243229/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_6_dldqt0.mp4",
      alt: "CONGCU.AI - Vòng Lặp Vĩnh Cửu",
      text: "CONGCU.AI | Trí Tuệ AI - Vòng Lặp Vĩnh Cửu",
      likes: 666,
      colSpan: "md:col-span-2",
      rowSpan: "row-span-2",
    },
    {
      id: 5,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774243230/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_7_xo4xow.mp4",
      alt: "CONGCU.AI - Ánh Sáng Ma Thuật",
      text: "CONGCU.AI | Trí Tuệ AI - Ánh Sáng Ma Thuật",
      likes: 555,
      colSpan: "",
      rowSpan: "row-span-3",
    },
    {
      id: 6,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774247641/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_10_lgqopq.mp4",
      alt: "CONGCU.AI - Năng Lượng Tiên Phong",
      text: "CONGCU.AI | Trí Tuệ AI - Năng Lượng Tiên Phong",
      likes: 444,
      colSpan: "",
      rowSpan: "row-span-4",
    },
    {
      id: 7,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774247647/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_12_uvocbz.mp4",
      alt: "CONGCU.AI - Đa Chiều Không Gian",
      text: "CONGCU.AI | Trí Tuệ AI - Đa Chiều Không Gian",
      likes: 333,
      colSpan: "md:col-span-2",
      rowSpan: "row-span-2",
    },
    {
      id: 8,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774247776/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_14_sq0fkc.mp4",
      alt: "CONGCU.AI - Rực Rỡ Sắc Màu",
      text: "CONGCU.AI | Trí Tuệ AI - Rực Rỡ Sắc Màu",
      likes: 222,
      colSpan: "",
      rowSpan: "row-span-3",
    },
    {
      id: 9,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774247778/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_16_jvfk6x.mp4",
      alt: "CONGCU.AI - Siêu Thực Điện Ảnh",
      text: "CONGCU.AI | Trí Tuệ AI - Siêu Thực Điện Ảnh",
      likes: 111,
      colSpan: "",
      rowSpan: "row-span-3",
    },
    {
      id: 10,
      src: "https://res.cloudinary.com/dm1li9fb8/video/upload/v1774247797/Thi%E1%BA%BFt_k%E1%BA%BF_ch%C6%B0a_c%C3%B3_t%C3%AAn_13_vi6pbp.mp4",
      alt: "CONGCU.AI - Kiệt Tác Thị Giác",
      text: "CONGCU.AI | Trí Tuệ AI - Kiệt Tác Thị Giác",
      likes: 88,
      colSpan: "",
      rowSpan: "row-span-2",
    }
];